FROM python:3.10-slim

ENV day 0

COPY input input/

WORKDIR /python

COPY python/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY python ./

CMD python advent_of_code.py ${day}